### ISSUE TITLE
Progressbar clears the whole console on disposing when no messages are posted

### ISSUE THREAD

**Issue by p-smith** [perryflynn/PerrysNetConsole#1]
Consider the following sample code:

    CoEx.WriteLine("Here");
    CoEx.WriteLine("are");
    CoEx.WriteLine("some");
    CoEx.WriteLine("lines");
    CoEx.WriteLine();

    var pbar = new Progress();
    pbar.Start();

    Thread.Sleep(2000);
    pbar.Update(50);

    Thread.Sleep(2000);
    pbar.Dispose();

    CoEx.WriteLine("Progressbar cleared.");

After pbar.Dispose() is called, the whole console is cleared including the lines written to the console before the progressbar:

![pb_clears_everything](https://user-images.githubusercontent.com/3879358/50638770-44144680-0f5f-11e9-9da4-1061cd7e1fe9.gif)

Interestingly, Dispose() works correctly if messages are posted to the progressbar:

![pb_clear_ok](https://user-images.githubusercontent.com/3879358/50638857-80e03d80-0f5f-11e9-9e43-c45fa20e8d16.gif)

**Comment by perryflynn** [comment]
Which version did you tried? 
Is the current alpha (Pre-Version for the new .NET Standard Build) affected?

**Comment by p-smith** [comment]
Yes, it was 2.0.0-alpha.

**Comment by perryflynn** [comment]
A new version is online on nuget.
Thanks for the bug report.

**Comment by p-smith** [comment]
Thanks for the fix, it's working fine now.
